<?php 

include 'core/init.php';
protect_page();
admin_protect();
include 'includes/head.php';

include 'includes/header.php';
 ?>

	<div id="content">
			<?php 
			if(logged_in() === false){
				include 'login.php';
			} else {
				include 'widgets/loggedin.php';
			}

			?>
			<h3 class="main-header">Admin</h3>
			<div id="main-content">
			
			<div class="article">
				<div class="article-title"><span class="icon-file-new"></span><h3>Publish New Article</h3></div>
				<form class="admin" action="publish-articles.php" method="POST" enctype="multipart/form-data">
				<ul>
				<li>
				Choose category:
				<select name="category">
					<option>Rants</option>
					<option>Tips and Tricks</option>
					<option>Opinions</option>
					<option>Travel</option>
					<option>Reviews</option>
					<option>Music</option>
					<option>Film</option>
					<option>Literature</option>
					<option>History</option>
					<option>Astronomy</option>
					<option>Sports</option>
					<option>Uncategorised</option>
				</select>
				</li>
				<li>Article Title:*<br />
				<input type="text" name="title" class="field"/>
				</li>
				<li>Choose Icon:
				<div class="select-holder">
				<select name="icon" class="select-icon">
					<option selected>icon-address-book-alt</option>
					<option>icon-adjust</option>
					<option>icon-adult</option>
					<option>icon-align-center</option>
					<option>icon-align-justify</option>
					<option>icon-align-left</option>
					<option>icon-align-right</option>
					<option>icon-arrow-down</option>
					<option>icon-arrow-left</option>
					<option>icon-arrow-right</option>
					<option>icon-arrow-up</option>
					<option>icon-asl</option>
					<option>icon-asterisk</option>
					<option>icon-backward</option>
					<option>icon-ban-circle</option>
					<option>icon-barcode</option>
					<option>icon-behance</option>
					<option>icon-bell</option>
					<option>icon-blind</option>
					<option>icon-blogger</option>
					<option>icon-bold</option>
					<option>icon-book</option>
					<option>icon-bookmark</option>
					<option>icon-bookmark-empty</option>
					<option>icon-braille</option>
					<option>icon-briefcase</option>
					<option>icon-broom</option>
					<option>icon-bullhorn</option>
					<option>icon-calendar</option>
					<option>icon-calendar-sign</option>
					<option>icon-camera</option>
					<option>icon-caret-down</option>
					<option>icon-caret-left</option>
					<option>icon-caret-right</option>
					<option>icon-caret-up</option>
					<option>icon-cc</option>
					<option>icon-certificate</option>
					<option>icon-check</option>
					<option>icon-check-empty</option>
					<option>icon-chevron-down</option>
					<option>icon-chevron-left</option>
					<option>icon-chevron-right</option>
					<option>icon-chevron-up</option>
					<option>icon-child</option>
					<option>icon-circle-arrow-down</option>
					<option>icon-circle-arrow-left</option>
					<option>icon-circle-arrow-right</option>
					<option>icon-circle-arrow-up</option>
					<option>icon-cloud</option>
					<option>icon-cloud-alt</option>
					<option>icon-cog</option>
					<option>icon-cog-alt</option>
					<option>icon-cogs</option>
					<option>icon-comment</option>
					<option>icon-comment-alt</option>
					<option>icon-compass</option>
					<option>icon-compass-alt</option>
					<option>icon-credit-card</option>
					<option>icon-css</option>
					<option>icon-dashboard</option>
					<option>icon-delicious</option>
					<option>icon-deviantart</option>
					<option>icon-digg</option>
					<option>icon-download</option>
					<option>icon-download-alt</option>
					<option>icon-dribble</option>
					<option>icon-edit</option>
					<option>icon-eject</option>
					<option>icon-envelope</option>
					<option>icon-envelope-alt</option>
					<option>icon-error</option>
					<option>icon-error-alt</option>
					<option>icon-exclamation-sign</option>
					<option>icon-eye-close</option>
					<option>icon-eye-open</option>
					<option>icon-facebook</option>
					<option>icon-facetime-video</option>
					<option>icon-fast-backward</option>
					<option>icon-fast-forward</option>
					<option>icon-female</option>
					<option>icon-file</option>
					<option>icon-file-alt</option>
					<option>icon-file-edit</option>
					<option>icon-file-edit-alt</option>
					<option>icon-file-new</option>
					<option>icon-file-new-alt</option>
					<option>icon-film</option>
					<option>icon-filter</option>
					<option>icon-fire</option>
					<option>icon-flag</option>
					<option>icon-flag-alt</option>
					<option>icon-flickr</option>
					<option>icon-folder</option>
					<option>icon-folder-close</option>
					<option>icon-folder-open</option>
					<option>icon-folder-sign</option>
					<option>icon-font</option>
					<option>icon-fontsize</option>
					<option>icon-fork</option>
					<option>icon-forward</option>
					<option>icon-forward-alt</option>
					<option>icon-foursquare</option>
					<option>icon-friendfeed</option>
					<option>icon-friendfeed-rect</option>
					<option>icon-fullscreen</option>
					<option>icon-gift</option>
					<option>icon-github</option>
					<option>icon-github-text</option>
					<option>icon-glass</option>
					<option>icon-glasses</option>
					<option>icon-globe</option>
					<option>icon-globe-alt</option>
					<option>icon-googleplus</option>
					<option>icon-graph</option>
					<option>icon-group</option>
					<option>icon-group-alt</option>
					<option>icon-guidedog</option>
					<option>icon-hand-down</option>
					<option>icon-hand-left</option>
					<option>icon-hand-right</option>
					<option>icon-hand-up</option>
					<option>icon-hdd</option>
					<option>icon-headphones</option>
					<option>icon-hearing-impaired</option>
					<option>icon-heart</option>
					<option>icon-heart-alt</option>
					<option>icon-heart-empty</option>
					<option>icon-home</option>
					<option>icon-home-alt</option>
					<option>icon-idea</option>
					<option>icon-idea-alt</option>
					<option>icon-inbox</option>
					<option>icon-inbox-alt</option>
					<option>icon-inbox-box</option>
					<option>icon-indent-left</option>
					<option>icon-indent-right</option>
					<option>icon-info-sign</option>
					<option>icon-instagram</option>
					<option>icon-iphone-home</option>
					<option>icon-italic</option>
					<option>icon-key</option>
					<option>icon-laptop</option>
					<option>icon-laptop-alt</option>
					<option>icon-lastfm</option>
					<option>icon-leaf</option>
					<option>icon-linkedin</option>
					<option>icon-list</option>
					<option>icon-list-alt</option>
					<option>icon-livejournal</option>
					<option>icon-lock</option>
					<option>icon-lock-alt</option>
					<option>icon-magnet</option>
					<option>icon-male</option>
					<option>icon-map-marker</option>
					<option>icon-map-marker-alt</option>
					<option>icon-mic</option>
					<option>icon-mic-sign</option>
					<option>icon-minus</option>
					<option>icon-minus-sign</option>
					<option>icon-move</option>
					<option>icon-music</option>
					<option>icon-myspace</option>
					<option>icon-network</option>
					<option>icon-off</option>
					<option>icon-ok</option>
					<option>icon-ok-circle</option>
					<option>icon-ok-sign</option>
					<option>icon-paper-clip</option>
					<option>icon-paper-clip-alt</option>
					<option>icon-path</option>
					<option>icon-pause</option>
					<option>icon-pause-alt</option>
					<option>icon-pencil</option>
					<option>icon-pencil-alt</option>
					<option>icon-person</option>
					<option>icon-phone</option>
					<option>icon-photo</option>
					<option>icon-photo-alt</option>
					<option>icon-picasa</option>
					<option>icon-picture</option>
					<option>icon-pinterest</option>
					<option>icon-plane</option>
					<option>icon-play</option>
					<option>icon-play-alt</option>
					<option>icon-play-circle</option>
					<option>icon-plus</option>
					<option>icon-plus-sign</option>
					<option>icon-print</option>
					<option>icon-qrcode</option>
					<option>icon-question</option>
					<option>icon-quotes</option>
					<option>icon-quotes-alt</option>
					<option>icon-random</option>
					<option>icon-record</option>
					<option>icon-reddit</option>
					<option>icon-refresh</option>
					<option>icon-remove</option>
					<option>icon-remove-circle</option>
					<option>icon-remove-sign</option>
					<option>icon-repeat</option>
					<option>icon-repeat-alt</option>
					<option>icon-resize-full</option>
					<option>icon-resize-horizontal</option>
					<option>icon-resize-small</option>
					<option>icon-resize-vertical</option>
					<option>icon-return-key</option>
					<option>icon-retweet</option>
					<option>icon-reverse-alt</option>
					<option>icon-road</option>
					<option>icon-rss</option>
					<option>icon-screen</option>
					<option>icon-screen-alt</option>
					<option>icon-screenshot</option>
					<option>icon-search</option>
					<option>icon-search-alt</option>
					<option>icon-share</option>
					<option>icon-share-alt</option>
					<option>icon-shopping-cart</option>
					<option>icon-shopping-cart-sign</option>
					<option>icon-signal</option>
					<option>icon-skype</option>
					<option>icon-slideshare</option>
					<option>icon-smiley</option>
					<option>icon-smiley-alt</option>
					<option>icon-soundcloud</option>
					<option>icon-speaker</option>
					<option>icon-spotify</option>
					<option>icon-stackoverflow</option>
					<option>icon-star</option>
					<option>icon-star-alt</option>
					<option>icon-star-empty</option>
					<option>icon-step-backward</option>
					<option>icon-step-forward</option>
					<option>icon-stop</option>
					<option>icon-stop-alt</option>
					<option>icon-stumbleupon</option>
					<option>icon-tag</option>
					<option>icon-tags</option>
					<option>icon-tasks</option>
					<option>icon-text-height</option>
					<option>icon-text-width</option>
					<option>icon-th</option>
					<option>icon-th-large</option>
					<option>icon-th-list</option>
					<option>icon-thumbs-down</option>
					<option>icon-thumbs-up</option>
					<option>icon-time</option>
					<option>icon-time-alt</option>
					<option>icon-tint</option>
					<option>icon-torso</option>
					<option>icon-trash</option>
					<option>icon-trash-alt</option>
					<option>icon-tumblr</option>
					<option>icon-twitter</option>
					<option>icon-universal-access</option>
					<option>icon-unlock</option>
					<option>icon-unlock-alt</option>
					<option>icon-upload</option>
					<option>icon-user</option>
					<option>icon-viadeo</option>
					<option>icon-video</option>
					<option>icon-video-alt</option>
					<option>icon-video-chat</option>
					<option>icon-view-mode</option>
					<option>icon-vimeo</option>
					<option>icon-vkontakte</option>
					<option>icon-volume-down</option>
					<option>icon-volume-up</option>
					<option>icon-w3c</option>
					<option>icon-warning-sign</option>
					<option>icon-website</option>
					<option>icon-website-alt</option>
					<option>icon-wheelchair</option>
					<option>icon-wordpress</option>
					<option>icon-wrench</option>
					<option>icon-wrench-alt</option>
					<option>icon-youtube</option>
					<option>icon-zoom-in</option>
					<option>icon-zoom-out</option>
				</select>
				<div id="icon-preview"></div>
				</div>
				</li>
				<li>Body:*<br />
				<textarea name="body" class="ckeditor text"></textarea>
				</li>
				<li>
				<input type="file" name="images[]" multiple="multiple" />
				</li>
				<li>Link: <br />
				<input type="text" name="link" class="field" />
				</li>
				<li>
				Tags:
				<div class="select-holder">
				<select name="tags" id="tag-selector">
				<!-- Maximum of 5 tags per article, for efficiency
					 Tried to cover as many as I could :)
				
					 Assuming these are under Tips and Tricks -->
					<option>php</option>
					<option>html</option>
					<option>css3</option>
					<option>jquery</option>
					<option>ajax</option>
					<option>mysql</option>
					<option>asp</option>
					<option>javascript</option>
					<option>web</option>
					<option>internet</option>
					<option>browser</option>
					<option>chrome</option>
					<option>ie</option>
					<option>firefox</option>
					<option>safari</option>
					<option>notepad++</option>
					<option>dreamweaver</option>
					<option>editor</option>
					<option>sublimetext</option>
					<option>text</option>
					<option>bluefish</option>
					<option>coda</option>
					<option>windows</option>
					<option>unix</option>
					<option>mac</option>
					<option>abletonlive</option>
					<option>fruityloops</option>
					<option>massive</option>
					<option>absynth</option>
					<option>fm8</option>
					<option>vst</option>
					<option>instrument</option>
					<option>keyboard</option>
					<option>piano</option>
					<option>guitar</option>
					<option>violin</option>
					<option>cello</option>
					<option>flute</option>
					<option>lessons</option>
					<option>music</option>
					<option>theory</option>
					<option>arts</option>
					<option>performance</option>
					<option>electronic</option>
					<option>production</option>
					<option>daw</option>
					<option>dj</option>
					<option>mixer</option>
					<option>headphones</option>
					<option>synthesis</option>
					<option>subtractive</option>
					<option>additive</option>
					<option>lfo</option>
					<option>oscillators</option>
					<option>equalizing</option>
					<option>mastering</option>
					<option>sound</option>
					<option>engineering</option>
					<option>design</option>
					<option>dubstep</option>
					<option>bass</option>
					<option>pads</option>
					<option>ambience</option>
					<option>stabs</option>
					<option>leads</option>
					<option>reverb</option>
					<option>delay</option>
					<option>compression</option>
					<option>trance</option>
					<option>techno</option>
					<option>house</option>
					<option>tribal</option>
					<option>percussion</option>
					<option>ethnic</option>
					<option>dnb</option>
					<option>composing</option>
					<option>writing</option>
					<option>ubuntu</option>
					<option>opensuse</option>
					<option>mint</option>
					<option>gnome</option>
					<option>kde</option>
					<option>cinnamon</option>
					<option>unity</option>
					<option>android</option>
					<option>development</option>
					<option>eclipse</option>
					<option>netbeans</option>
					<option>java</option>
					<option>sql</option>
					<option>adobe</option>
					<option>dreamweaver</option>
					<option>photoshop</option>
					<option>fireworks</option>
					<option>illustrator</option>
					<option>graphics</option>
					<option>animation</option>
					<option>plugins</option>
					<option>gimp</option>
					<option>tutorials</option>
					<option>youtube</option>
					<option>videos</option>
					<option>resources</option>
					<option>learning</option>
					<option>mac</option>
					<option>sass</option>
					<option>less</option>
					<option>preprocessor</option>
					<option>fonts</option>
					<option>icons</option>
					<option>free</option>
					<option>paid</option>
					<option>cheats</option>
					<option>patches</option>
					<option>cracks</option>
					<option>howto</option>
					<option>games</option>
					<option>arcade</option>
					<option>racing</option>
					<option>football</option>
					<option>basketball</option>
					<option>fighter</option>
					<option>extreme</option>
					<option>rally</option>
					<option>wrestling</option>
					<option>motocross</option>
					<option>f1</option>
					<option>superbike</option>
					<option>playstation</option>
					<option>pc</option>
					<option>xbox</option>
					<option>bluetooth</option>
					<option>bluray</option>
					<option>download</option>
					<option>network</option>
					<option>lan</option>
					<option>speed</option>
					<option>throttle</option>
					<option>graphics</option>
					<option>vga</option>
					<option>needforspeed</option>
					<option>fifa</option>
					<option>callofduty</option>
					<option>gearsofwar</option>
					<option>modem</option>
					<option>unlocking</option>
					<option>password</option>
					<option>hack</option>
					<option>torrents</option>
					<option>overclocking</option>
					
				<!-- Assuming these are under Reviews -->
					<option>phones</option>
					<option>smart</option>
					<option>lg</option>
					<option>samsung</option>
					<option>htc</option>
					<option>huawei</option>
					<option>nokia</option>
					<option>alcatel</option>
					<option>iphone</option>
					<option>windows</option>
					<option>ios</option>
					<option>linux</option>
					<option>android</option>
					<option>ubuntu</option>
					<option>mint</option>
					<option>opensuse</option>
					<option>symbian</option>
					<option>apps</option>
					<option>websites</option>
					<option>electronics</option>
					<option>cars</option>
					<option>computers</option>
					<option>hp</option>
					<option>dell</option>
					<option>alienware</option>
					<option>acer</option>
					<option>displays</option>
					<option>graphics</option>
					<option>vga</option>
					<option>vga</option>
					<option>highend</option>
					<option>budget</option>
					<option>toshiba</option>
					<option>origin</option>
					<option>intel</option>
					<option>processors</option>
					<option>ram</option>
					<option>lenovo</option>
					<option>tablet</option>
					<option>amd</option>
					<option>mouse</option>
					<option>keyboard</option>
					<option>gaming</option>
					<option>modems</option>
					<option>Internet</option>
					<option>connectivity</option>
					<option>ISP</option>
					<option>sharing</option>
					<option>software</option>
					<option>hardware</option>
					<option>operating</option>
					<option>systems</option>
					<option>shops</option>
					<option>offers</option>
					<option>speed</option>
					
					
				<!-- Assuming these are under Music -->
					<option>trance</option>
					<option>house</option>
					<option>techno</option>
					<option>dubstep</option>
					<option>complextro</option>
					<option>electronic</option>
					<option>asot</option>
					<option>abgt</option>
					<option>arminvanbuuren</option>
					<option>aboveandbeyond</option>
					<option>alyandfila</option>
					<option>fsoe</option>
					<option>kenyan</option>
					<option>southafrican</option>
					<option>afrohouse</option>
					<option>tribalhouse</option>
					<option>uplifting</option>
					<option>psychedelic</option>
					<option>hardstyle</option>
					<option>mixes</option>
					<option>kwaito</option>
					<option>world</option>
					<option>ethnic</option>
					<option>african</option>
					<option>westafrican</option>
					<option>bongo</option>
					<option>ugandan</option>
					<option>dance</option>
					<option>afropop</option>
					<option>genge</option>
					<option>boomba</option>
					<option>rock</option>
					<option>jazz</option>
					<option>smooth</option>
					<option>classics</option>
					<option>asian</option>
					<option>british</option>
					<option>alternative</option>
					<option>metal</option>
					<option>folk</option>
					<option>neosoul</option>
					<option>soul</option>
					<option>bet</option>
					<option>contemporary</option>
					<option>gospel</option>
					<option>piano</option>
					<option>guitar</option>
					<option>flute</option>
					<option>saxophone</option>
					<option>marimba</option>
					<option>instruments</option>
					<option>violin</option>
					<option>cello</option>
					<option>ambient</option>
					<option>soundtracks</option>
					<option>scores</option>
					<option>cinematics</option>
					<option>soundscapes</option>
					<option>effects</option>
					<option>mixcloud</option>
					<option>soundcloud</option>
					<option>link</option>

				<!-- Assuming these are under Rants -->
				
				<!-- Assuming these are under Opinion -->
				
				<!-- Assuming these are under Travel -->
					<option>out</option>
					<option>about</option>
					<option>photos</option>
					<option>food</option>
					<option>joints</option>
					<option>pubs</option>
					<option>dinners</option>
					<option>fun</option>
					<option>hotels</option>
					<option>lunch</option>
					<option>parks</option>
					<option>wildlife</option>
					<option>tours</option>
					<option>transport</option>
					<option>roads</option>
					<option>sights</option>
					<option>monuments</option>
					<option>interests</option>
					<option>marine</option>
					<option>geology</option>
					<option>wonders</option>
					<option>rural</option>
					<option>urban</option>
					<option>fares</option>
					<option>distances</option>
					<option>GPS</option>
					<option>cars</option>
					<option>exploration</option>
					<option>deep</option>
					
				
				<!-- Assuming these are under Video -->
					<option>youtube</option>
					<option>dailymotion</option>
					<option>kenyan</option>
					<option>movies</option>
					<option>clips</option>
					<option>scores</option>
					<option>soundtrack</option>
					<option>tutorials</option>
					<option>tips</option>
					<option>tricks</option>
					<option>animation</option>
					<option>TV</option>
					<option>production</option>
					<option>anime</option>
					<option>cartoons</option>
					
				
				<!-- Assuming these are under History -->
				
				<!-- Assuming these are under Astronomy -->
					<option>galaxy</option>
					<option>universe</option>
					<option>multiverse</option>
					<option>theory</option>
					<option>aliens</option>
					<option>extraterrestrials</option>
					<option>space</option>
					<option>technology</option>
					<option>telescope</option>
					<option>stars</option>
					<option>planets</option>
					<option>comets</option>
					<option>comets</option>
					<option>meteors</option>
					<option>showers</option>
					<option>perseids</option>
					<option>crater</option>
					<option>mercury</option>
					<option>venus</option>
					<option>earth</option>
					<option>mars</option>
					<option>jupiter</option>
					<option>saturn</option>
					<option>uranus</option>
					<option>neptune</option>
					<option>pluto</option>
					<option>exploration</option>
					<option>deep</option>
					<option>interstellar</option>
					<option>probes</option>
					<option>conspiracies</option>
					<option>NASA</option>
					<option>airforce</option>
					<option>army</option>
					<option>astronauts</option>
					<option>cosmonauts</option>
					<option>ISS</option>
					<option>shuttle</option>
					<option>rocket</option>
					<option>propulsion</option>
					<option>gravity</option>
					<option>supersonic</option>
					<option>physics</option>
					<option>weather</option>
					<option>satellites</option>
					<option>moon</option>
					<option>eclipse</option>
					<option>stars</option>
					<option>sun</option>
					<option>milkyway</option>
					<option>blackholes</option>
					<option>whitedwarfs</option>
					<option>redgiants</option>
					<option>supenovas</option>
					<option>quasars</option>
					<option>cosmic</option>
					<option>aurora</option>
					<option>borealis</option>
					<option>northern</option>
					<option>lights</option>
					<option>solar</option>
					<option>flare</option>
					<option>wind</option>
					<option>emp</option>
					<option>spots</option>
					<option>field</option>
					<option>magnetic</option>
					<option>compass</option>
					<option>crust</option>
					<option>tides</option>
					<option>oceans</option>
					<option>volcanoes</option>
					<option>geology</option>
					<option>ice</option>
					<option>water</option>
					<option>life</option>
					<option>observatories</option>
					<option>sky</option>
					<option>watching</option>
					<option>amateur</option>
					<option>camera</option>
					<option>hubble</option>
					<option>constellations</option>
					<option>myths</option>
					<option>spaceships</option>
					<option>scifi</option>
					<option>kidnappings</option>
					<option>flying</option>
					<option>saucers</option>
					<option>government</option>
					<option>coverups</option>
					<option>mib</option>
					<option>baloons</option>
					<option>suits</option>
					<option>navigation</option>
					<option>horoscopes</option>
					<option>dust</option>
					<option>energy</option>
					<option>sonic</option>
					<option>boom</option>
					<option>tragedies</option>
					<option>catastrophies</option>
					<option>extinction</option>
				
				<!-- Assuming these are under Literature -->
				
				</select>
				<div class="tag-preview">
					
				</div>
				</div>
				</li>
				<div class="clear"></div>
				<li><p>
				<input class="button" type="submit" value="Publish" />
				</li>
				</ul>
				</form>
			</div>
			
			<div class="article">
				<div class="article-title"><span class="icon-file-edit"></span><h3>Edit Article</h3></div>
				<form class="admin" action="edit-articles.php" method="POST">
				<ul>
				<li>Enter Article Number:<br />
				<input type="text" name="article_id" class="article_id" />
				</li>
				<li>
				Choose category:
				<select name="category">
					<option>Rants</option>
					<option>Tips and Tricks</option>
					<option>My Opinions</option>
					<option>Out and About</option>
					<option>Reviews</option>
					<option>Uncategorised</option>
				</select>
				</li>
				<li>Article Title:*<br />
				<input type="text" name="title" class="field" id="article_title" />
				</li>
				<li>Choose Icon:
				<div class="select-holder">
				<select name="icon" class="select-icon">
					<option selected>icon-address-book-alt</option>
					<option>icon-adjust</option>
					<option>icon-adult</option>
					<option>icon-align-center</option>
					<option>icon-align-justify</option>
					<option>icon-align-left</option>
					<option>icon-align-right</option>
					<option>icon-arrow-down</option>
					<option>icon-arrow-left</option>
					<option>icon-arrow-right</option>
					<option>icon-arrow-up</option>
					<option>icon-asl</option>
					<option>icon-asterisk</option>
					<option>icon-backward</option>
					<option>icon-ban-circle</option>
					<option>icon-barcode</option>
					<option>icon-behance</option>
					<option>icon-bell</option>
					<option>icon-blind</option>
					<option>icon-blogger</option>
					<option>icon-bold</option>
					<option>icon-book</option>
					<option>icon-bookmark</option>
					<option>icon-bookmark-empty</option>
					<option>icon-braille</option>
					<option>icon-briefcase</option>
					<option>icon-broom</option>
					<option>icon-bullhorn</option>
					<option>icon-calendar</option>
					<option>icon-calendar-sign</option>
					<option>icon-camera</option>
					<option>icon-caret-down</option>
					<option>icon-caret-left</option>
					<option>icon-caret-right</option>
					<option>icon-caret-up</option>
					<option>icon-cc</option>
					<option>icon-certificate</option>
					<option>icon-check</option>
					<option>icon-check-empty</option>
					<option>icon-chevron-down</option>
					<option>icon-chevron-left</option>
					<option>icon-chevron-right</option>
					<option>icon-chevron-up</option>
					<option>icon-child</option>
					<option>icon-circle-arrow-down</option>
					<option>icon-circle-arrow-left</option>
					<option>icon-circle-arrow-right</option>
					<option>icon-circle-arrow-up</option>
					<option>icon-cloud</option>
					<option>icon-cloud-alt</option>
					<option>icon-cog</option>
					<option>icon-cog-alt</option>
					<option>icon-cogs</option>
					<option>icon-comment</option>
					<option>icon-comment-alt</option>
					<option>icon-compass</option>
					<option>icon-compass-alt</option>
					<option>icon-credit-card</option>
					<option>icon-css</option>
					<option>icon-dashboard</option>
					<option>icon-delicious</option>
					<option>icon-deviantart</option>
					<option>icon-digg</option>
					<option>icon-download</option>
					<option>icon-download-alt</option>
					<option>icon-dribble</option>
					<option>icon-edit</option>
					<option>icon-eject</option>
					<option>icon-envelope</option>
					<option>icon-envelope-alt</option>
					<option>icon-error</option>
					<option>icon-error-alt</option>
					<option>icon-exclamation-sign</option>
					<option>icon-eye-close</option>
					<option>icon-eye-open</option>
					<option>icon-facebook</option>
					<option>icon-facetime-video</option>
					<option>icon-fast-backward</option>
					<option>icon-fast-forward</option>
					<option>icon-female</option>
					<option>icon-file</option>
					<option>icon-file-alt</option>
					<option>icon-file-edit</option>
					<option>icon-file-edit-alt</option>
					<option>icon-file-new</option>
					<option>icon-file-new-alt</option>
					<option>icon-film</option>
					<option>icon-filter</option>
					<option>icon-fire</option>
					<option>icon-flag</option>
					<option>icon-flag-alt</option>
					<option>icon-flickr</option>
					<option>icon-folder</option>
					<option>icon-folder-close</option>
					<option>icon-folder-open</option>
					<option>icon-folder-sign</option>
					<option>icon-font</option>
					<option>icon-fontsize</option>
					<option>icon-fork</option>
					<option>icon-forward</option>
					<option>icon-forward-alt</option>
					<option>icon-foursquare</option>
					<option>icon-friendfeed</option>
					<option>icon-friendfeed-rect</option>
					<option>icon-fullscreen</option>
					<option>icon-gift</option>
					<option>icon-github</option>
					<option>icon-github-text</option>
					<option>icon-glass</option>
					<option>icon-glasses</option>
					<option>icon-globe</option>
					<option>icon-globe-alt</option>
					<option>icon-googleplus</option>
					<option>icon-graph</option>
					<option>icon-group</option>
					<option>icon-group-alt</option>
					<option>icon-guidedog</option>
					<option>icon-hand-down</option>
					<option>icon-hand-left</option>
					<option>icon-hand-right</option>
					<option>icon-hand-up</option>
					<option>icon-hdd</option>
					<option>icon-headphones</option>
					<option>icon-hearing-impaired</option>
					<option>icon-heart</option>
					<option>icon-heart-alt</option>
					<option>icon-heart-empty</option>
					<option>icon-home</option>
					<option>icon-home-alt</option>
					<option>icon-idea</option>
					<option>icon-idea-alt</option>
					<option>icon-inbox</option>
					<option>icon-inbox-alt</option>
					<option>icon-inbox-box</option>
					<option>icon-indent-left</option>
					<option>icon-indent-right</option>
					<option>icon-info-sign</option>
					<option>icon-instagram</option>
					<option>icon-iphone-home</option>
					<option>icon-italic</option>
					<option>icon-key</option>
					<option>icon-laptop</option>
					<option>icon-laptop-alt</option>
					<option>icon-lastfm</option>
					<option>icon-leaf</option>
					<option>icon-linkedin</option>
					<option>icon-list</option>
					<option>icon-list-alt</option>
					<option>icon-livejournal</option>
					<option>icon-lock</option>
					<option>icon-lock-alt</option>
					<option>icon-magnet</option>
					<option>icon-male</option>
					<option>icon-map-marker</option>
					<option>icon-map-marker-alt</option>
					<option>icon-mic</option>
					<option>icon-mic-sign</option>
					<option>icon-minus</option>
					<option>icon-minus-alt</option>
					<option>icon-move</option>
					<option>icon-music</option>
					<option>icon-myspace</option>
					<option>icon-network</option>
					<option>icon-off</option>
					<option>icon-ok</option>
					<option>icon-ok-circle</option>
					<option>icon-ok-sign</option>
					<option>icon-paper-clip</option>
					<option>icon-paper-clip-alt</option>
					<option>icon-path</option>
					<option>icon-pause</option>
					<option>icon-pause-alt</option>
					<option>icon-pencil</option>
					<option>icon-pencil-alt</option>
					<option>icon-person</option>
					<option>icon-phone</option>
					<option>icon-photo</option>
					<option>icon-photo-alt</option>
					<option>icon-picasa</option>
					<option>icon-picture</option>
					<option>icon-pinterest</option>
					<option>icon-plane</option>
					<option>icon-play</option>
					<option>icon-play-alt</option>
					<option>icon-play-circle</option>
					<option>icon-plus</option>
					<option>icon-plus-sign</option>
					<option>icon-print</option>
					<option>icon-qrcode</option>
					<option>icon-question</option>
					<option>icon-quotes</option>
					<option>icon-quotes-alt</option>
					<option>icon-random</option>
					<option>icon-record</option>
					<option>icon-reddit</option>
					<option>icon-refresh</option>
					<option>icon-remove</option>
					<option>icon-remove-circle</option>
					<option>icon-remove-sign</option>
					<option>icon-repeat</option>
					<option>icon-repeat-alt</option>
					<option>icon-resize-full</option>
					<option>icon-resize-horizontal</option>
					<option>icon-resize-small</option>
					<option>icon-resize-vertical</option>
					<option>icon-return-key</option>
					<option>icon-retweet</option>
					<option>icon-reverse-alt</option>
					<option>icon-road</option>
					<option>icon-rss</option>
					<option>icon-screen</option>
					<option>icon-screen-alt</option>
					<option>icon-screenshot</option>
					<option>icon-search</option>
					<option>icon-search-alt</option>
					<option>icon-share</option>
					<option>icon-share-alt</option>
					<option>icon-shopping-cart</option>
					<option>icon-shopping-cart-sign</option>
					<option>icon-signal</option>
					<option>icon-skype</option>
					<option>icon-slideshare</option>
					<option>icon-smiley</option>
					<option>icon-smiley-alt</option>
					<option>icon-soundcloud</option>
					<option>icon-speaker</option>
					<option>icon-spotify</option>
					<option>icon-stackoverflow</option>
					<option>icon-star</option>
					<option>icon-star-alt</option>
					<option>icon-star-empty</option>
					<option>icon-step-backward</option>
					<option>icon-step-forward</option>
					<option>icon-stop</option>
					<option>icon-stop-alt</option>
					<option>icon-stumbleupon</option>
					<option>icon-tag</option>
					<option>icon-tags</option>
					<option>icon-tasks</option>
					<option>icon-text-height</option>
					<option>icon-text-width</option>
					<option>icon-th</option>
					<option>icon-th-large</option>
					<option>icon-th-list</option>
					<option>icon-thumbs-down</option>
					<option>icon-thumbs-up</option>
					<option>icon-time</option>
					<option>icon-time-alt</option>
					<option>icon-tint</option>
					<option>icon-torso</option>
					<option>icon-trash</option>
					<option>icon-trash-alt</option>
					<option>icon-tumblr</option>
					<option>icon-twitter</option>
					<option>icon-universal-access</option>
					<option>icon-unlock</option>
					<option>icon-unlock-alt</option>
					<option>icon-upload</option>
					<option>icon-user</option>
					<option>icon-viadeo</option>
					<option>icon-video</option>
					<option>icon-video-alt</option>
					<option>icon-video-chat</option>
					<option>icon-view-mode</option>
					<option>icon-vimeo</option>
					<option>icon-vkontakte</option>
					<option>icon-volume-down</option>
					<option>icon-volume-up</option>
					<option>icon-w3c</option>
					<option>icon-warning-sign</option>
					<option>icon-website</option>
					<option>icon-website-alt</option>
					<option>icon-wheelchair</option>
					<option>icon-wordpress</option>
					<option>icon-wrench</option>
					<option>icon-wrench-alt</option>
					<option>icon-youtube</option>
					<option>icon-zoom-in</option>
					<option>icon-zoom-out</option>
				</select>
				<div id="icon-preview"></div>
				</div>
				</li>
				<li>Body:*<br />
				<textarea name="body" class="ckeditor text" id="article_text" ></textarea>
				</li>
				<li>
				<input type="file" name="media" />
				</li>
				<li>Link: <br />
				<input type="text" name="link" class="field" />
				</li>
				<li>
				Tags:
				<div class="select-holder">
				<select name="tags" id="tag-selector">
					<option>php</option>
					<option>html</option>
					<option>css3</option>
					<option>jquery</option>
					<option>ajax</option>
				</select>
				<div class="tag-preview">
					
				</div>
				</div>
				</li>
				<div class="clear"></div>
				<li><p>
				<input class="button" type="submit" value="Update" />
				</li>
				</ul>
				</form>
			</div>
			
			<div class="article">
				<div class="article-title"><span class="icon-trash"></span><h3>Delete Article</h3></div>
				<form class="admin" action="delete-articles.php" method="POST">
				<ul>
				<li>Enter Article Number:<br />
				<input type="text" name="article_id" />
				</li>
				<p>
				<ul>
				<li>Article Title:<br />
				<input type="text" name="title" />
				</li>
				<li><p>
				<input class="button" type="submit" value="Delete" />
				</li>
				</ul>
				</form>
			</div>
			
			</div>
		<div id="aside">
			<div id="feeds">
			Twitter feed here	
			</div>
			<div id="stats">
			Stats here			
			</div>	
		</div>
	</div>
	<div class="clear"></div>
<?php
	include 'includes/footer.php';
?>